// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAWWUSFxAJaMk6Xx3A4ggtRqY_vJTwILo',
    appId: '1:243013125958:web:bb916e1cb0f3d7913cc747',
    messagingSenderId: '243013125958',
    projectId: 'booking-app-19ce9',
    authDomain: 'booking-app-19ce9.firebaseapp.com',
    storageBucket: 'booking-app-19ce9.appspot.com',
    measurementId: 'G-FSQ4CVB55D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMCWGta29AERfoRSmBcFolJcy_ACmKY8k',
    appId: '1:243013125958:android:9ed8ad78bae1305e3cc747',
    messagingSenderId: '243013125958',
    projectId: 'booking-app-19ce9',
    storageBucket: 'booking-app-19ce9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqs1IhSlHT18vKeXslh3OL2BsX3jL7h4U',
    appId: '1:243013125958:ios:f6f7fe6bc1e282563cc747',
    messagingSenderId: '243013125958',
    projectId: 'booking-app-19ce9',
    storageBucket: 'booking-app-19ce9.appspot.com',
    iosBundleId: 'com.example.abodein',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqs1IhSlHT18vKeXslh3OL2BsX3jL7h4U',
    appId: '1:243013125958:ios:f6f7fe6bc1e282563cc747',
    messagingSenderId: '243013125958',
    projectId: 'booking-app-19ce9',
    storageBucket: 'booking-app-19ce9.appspot.com',
    iosBundleId: 'com.example.abodein',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAWWUSFxAJaMk6Xx3A4ggtRqY_vJTwILo',
    appId: '1:243013125958:web:6467590d675c72713cc747',
    messagingSenderId: '243013125958',
    projectId: 'booking-app-19ce9',
    authDomain: 'booking-app-19ce9.firebaseapp.com',
    storageBucket: 'booking-app-19ce9.appspot.com',
    measurementId: 'G-2M6VG17Z7H',
  );
}
